[package]
name = "awdl-frame-parser"
version = "0.2.1"
edition = "2021"
description = "A parser for AWDL data and action frames."
authors = ["Frostie314159"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Frostie314159/awdl-frame-parser"

[profile.release]
opt-level = 3

[features]
read = []
write = []
version_tlv = []
dns_sd_tlvs = []
data_tlvs = []
sync_elect_tlvs = []
data_frame = []
debug = []
fixed_chan_seq = []
all_tlvs = ["version_tlv", "dns_sd_tlvs", "data_tlvs", "sync_elect_tlvs"]
default = ["write", "read", "all_tlvs", "data_frame", "debug", "fixed_chan_seq"]

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "awdl_frame_parser"
harness = false
